name: CI

on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - run: cmake -G "Unix Makefiles" .
      - run: make
      - uses: actions/upload-artifact@v1
        with:
          name: build-linux
          path: src/lab
      - uses: actions/upload-artifact@v1
        with:
          name: tests-linux
          path: tests/tests
  test-linux:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: tests-linux
      - run: chmod +x tests-linux/tests
      - run: tests-linux/tests
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: cmake -G "Unix Makefiles" .
      - run: make
      - uses: actions/upload-artifact@v1
        with:
          name: build-windows
          path: src/lab.exe
      - uses: actions/upload-artifact@v1
        with:
          name: tests-windows
          path: tests/tests.exe
  test-windows:
    runs-on: windows-latest
    needs: build-windows
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: tests-windows
      - run: tests-windows\tests.exe
