name: CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: catchorg/Catch2
          ref: master
      - cd /home/runner/work/uk-nprg041-lab/Catch2
      - cmake -Bbuild -H. -DBUILD_TESTING=OFF
      - sudo cmake --build build/ --target install
      - uses: actions/checkout@v1 
      - run: cmake -G "Unix Makefiles" ./ && make
      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: src/lab
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: catchorg/Catch2
          ref: master
      - cd /home/runner/work/uk-nprg041-lab/Catch2
      - cmake -Bbuild -H. -DBUILD_TESTING=OFF
      - sudo cmake --build build/ --target install
      - uses: actions/checkout@v1
      - run: cmake -G "Unix Makefiles" ./ && make
      - run: make test
