name: CI

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1 
      - run: cmake -G "Unix Makefiles" ./ && make
      - uses: actions/upload-artifact@v1
        with:
          name: build-${{ matrix.os }}
          path: src/lab
      - uses: actions/upload-artifact@v1
        with:
          name: tests-${{ matrix.os }}
          path: tests/tests
  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: tests-${{ matrix.os }}
      - run: tests/tests
